- name: Frontend Playbook
  hosts: all
  become: yes
  tasks:
	- name: Disable Default Nginx
	  ansible.builtin.dnf: dnf module disable nginx -y

	- name: Enable nginx 24 version
	  ansible.builtin.dnf: dnf module nginx:1.24 -y

	- name: Install Nginx
	  ansible.builtin.dnf:
		name: Nginx
		state: present

	- name: Copy nginx config file
	  ansible.builtin.copy:
		src: nginx.conf

		dest: /etc/nginx/nginx.conf

	- name: start nginx
	  ansible.builtin.systemd_service:
		name: nginx
        state: started