- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Load Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load SQL File
  ansible.builtin.shell: mysql -h mysql-{{ env }}.devops11.online -uroot -p{{ lookup('hashi_vault', 'roboshop-{{ env }}/data/shipping:mysql_root_password token={{ vault_token }} url=http://vault-internal.devops11.online:8200')}} < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data

- name: restart Shipping
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted
